# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('average', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Common_words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(default=0)),
                ('rating', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('rating', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('positive', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('neutral', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('negative', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('word_count', models.IntegerField()),
                ('month_average', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
