# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common_words',
            name='frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='common_words',
            name='year',
            field=models.IntegerField(),
        ),
    ]
